media:
  input: media
  output: /media

content:
  - name: posts
    label: Posts
    path: src/posts
    type: collection
    icon: file-text
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: author
        label: Author
        type: string
        required: true
      - name: image
        label: Featured Image
        type: image
      - name: content
        label: Content
        type: rich-text
        required: true
    filename: "{year}-{month}-{day}-{fields.title}.md"
    view:
      fields: [title, date, author]
      primary: title
      sort: [date]
      default:
        sort: date
        order: desc