name: Update index.json

on:
  push:
    paths:
      - 'src/posts/**/*.md'

jobs:
  update-index:
    runs-on: ubuntu-latest
    # Add write permissions
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to latest version

      - name: Generate index.json
        run: |
          cd src/posts
          echo '[' > index.json
          for file in *.md; do
            title=$(grep -m 1 '^title:' "$file" | cut -d ':' -f 2 | sed 's/^ *//')
            date=$(grep -m 1 '^date:' "$file" | cut -d ':' -f 2 | sed 's/^ *//')
            author=$(grep -m 1 '^author:' "$file" | cut -d ':' -f 2 | sed 's/^ *//')
            echo "  { \"file\": \"$file\", \"title\": \"$title\", \"date\": \"$date\", \"author\": \"$author\" }," >> index.json
          done
          sed -i '$ s/,$//' index.json
          echo ']' >> index.json

      - name: Commit and push changes
        run: |
          # Use GitHub Actions bot credentials
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add src/posts/index.json
          git commit -m "Automatically update index.json"
          # Authenticate with GITHUB_TOKEN
          git push https://x-access-token:${{ secrets.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 }}@github.com/${{ github.repository }}.git HEAD:main
